### ISSUE TITLE
Several links broken in guide on website

### ISSUE THREAD

**Issue by jvmdc** [testcontainers/tc-guide-getting-started-with-testcontainers-for-dotnet#2]
On the page on "Getting started with Testcontainers for .NET" (https://testcontainers.com/guides/getting-started-with-testcontainers-for-dotnet/), several code snippets are missing, replaced by a box containing an error message similar to this:
```
Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/testcontainers/tc-guide-getting-started-with-testcontainers-for-dotnet/main/TestcontainersDemo/CustomerService/CustomerService.csproj[lines="10"]
```

It seems some files have been moved around without updating the website.

**Comment by kiview** [comment]
Render correctly for me, so I assume it got fixed already. Can you please ping again, if you see the issue persist @jvmdc? 🙏
